{{- if .Values.certManager.enabled }}
{{- if .Values.certManager.staging.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: {{ .Values.certManager.staging.email }}
    server: {{ .Values.certManager.staging.server }}
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          class: {{ .Values.ingress.className }}
{{- end }}
{{- end }}
