{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-db
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "openchat.db.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.postgresql.service.port }}
    targetPort: postgres
    protocol: TCP
    name: postgres
  selector:
    app: {{ .Values.app.name }}
    component: db
{{- end }}
