{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-redis
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "openchat.redis.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
      component: redis
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        component: redis
    spec:
      containers:
      - name: redis
        image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
        command:
        - redis-server
        - --appendonly
        - 'yes'
        ports:
        - name: redis
          containerPort: {{ .Values.redis.service.port }}
          protocol: TCP
        volumeMounts:
        - name: redis-data
          mountPath: /data
        resources:
          {{- toYaml .Values.redis.resources | nindent 10 }}
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: {{ .Values.redis.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.redis.livenessProbe.periodSeconds }}
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: {{ .Values.redis.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.redis.readinessProbe.periodSeconds }}
      volumes:
      - name: redis-data
        {{- if .Values.redis.persistence.enabled }}
        persistentVolumeClaim:
          claimName: redis-pvc
        {{- else }}
        emptyDir: {}
        {{- end }}
{{- end }}
