apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-web
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "openchat.web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
  - port: {{ .Values.web.service.port }}
    targetPort: {{ .Values.web.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.app.name }}
    component: web
