apiVersion: v1
kind: ConfigMap
metadata:
  name: openchat-config
  namespace: openchat
data:
  POSTGRES_HOST: "openchat-db"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "openchat"
  REDIS_URL: "redis://openchat-redis:6379/0"
  REDIS_HOST: "openchat-redis"
  DEBUG: "False"
  DJANGO_SETTINGS_MODULE: "openchat.settings.prod"
  ALLOWED_HOSTS: "*"
  CSRF_TRUSTED_ORIGINS: "https://rocketbyte.duckdns.org"
  SESSION_COOKIE_SECURE: "True"
  CSRF_COOKIE_SECURE: "True"
  SECURE_SSL_REDIRECT: "False"
